---

- hosts: kube-cluster
  become: yes
  roles:
    - { role: tools }
    - { role: ohmyzsh }
    - { role: docker }
    - { role: preinstall }

- hosts: master
  become: yes
  roles:
    - { role: master }
