---
- name: Installing Zsh and git
  apt:
    name:
      - zsh
      - git
    state: latest
    update_cache: yes

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/hamidfzm/ohmyzsh.git
    dest: ~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  when: not stat_rc_result.stat.exists

- name: Change shell
  user:
    name: "{{ansible_user_id}}"
    shell: /usr/bin/zsh

