---
- name: Installing zsh and git
  apt:
    name:
      - zsh
      - git
    state: latest
    update_cache: yes

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ item }}/.oh-my-zsh"
  with_items:
    - "/home/{{ ansible_ssh_user }}"
    - "~"

- name: Copy .zshrc
  template:
    src: .zshrc
    dest: "{{ item }}/.zshrc"
  with_items:
    - "/home/{{ ansible_ssh_user }}"
    - "~"

- name: Change shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ ansible_ssh_user }}"
    - "{{ ansible_user_id }}"
