---

- name: Installing tools (ohmyzsh)
  include_role:
    name: ohmyzsh

- name: Installing tools (others)
  apt:
    name:
      - htop
      - nmap
      - netcat
    state: latest
    update_cache: yes
