---

- name: Check if docker is configured
  stat:
    path: "/etc/docker/daemon.json"
  register: docker_daemon

- name: Init docker if needed
  include_tasks: init.yml
  when: not docker_daemon.stat.exists
  run_once: yes
