---
- name: Install Docker dependencies
  when: ansible_os_family == "Debian"
  apt:
    name:
      - apt-transport-https
      - gnupg
      - ca-certificates
    state: present
    update_cache: yes

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
    filename: "docker"

- name: Install docker engine (Debian)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "docker-ce={{ docker_version }}*"
    state: present

- name: Hold docker version
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold
